### PR TITLE
included relationships should use the data member

### PR DESCRIPTION
**Pull request by winglian**
relationships key should have a data member that should be searched/compared when looking for related objects

### CODE REVIEW

**Comment by winglian** [comment]
@alex94puchades looks like you were using the `value.data` in a previous version, but decided it was a bug in https://github.com/alex94puchades/superagent-jsonapify/commit/b5deece2c6529e7bd83902ae30925d15c39f4435 ? however this breaks matching multiple related resources.

**Comment by alex94puchades** [comment]
@winglian That's a great catch, really thank you!

**Comment by winglian** [comment]
@alex94puchades Thanks! let me know when you have a chance to bump the version and push to npm

**Comment by alex94puchades** [comment]
@winglian your changes have been included in the latest version (1.4.1)

**Pull request merged**
